server:
  port: 8080

spring:

  security:
    user:
      name: admin
      password: admin123

  jpa:
    database: mysql
    show-sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiqingyun
    username: root
    password: root123

  flyway:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiqingyun
    user: root
    password: root123
    locations: classpath:db/migration/mysql
    enabled: true

logging:
  level:
    root: info

isx-app:
  use-ssl: false
  resources-path: classpath:resources